### ISSUE TITLE
Can't use multi instance in same page

### ISSUE THREAD

**Issue by mohamedsabil83** [gwleuverink/blade-shape-divider#3]
As I said in the title, if you use multi divide on the same page, it will take the options from the first one. You can't use different shapes on the same page. It will be more useful if we can use multi-shapes on the same page.

e.g.:
```blade
<x-shape-divider
    shape="waves-opacity"
    class="text-blue-800"
/>
```
and
```blade
<x-shape-divider
    shape="split"
    class="text-blue-800"
/>
```
both will render a **waves-opacity** as it is placed in the first.

**Comment by gwleuverink** [comment]
Thanks for reaching out @mohamedsabil83. Yeah it should work that way. I’ll have a look at it

**Comment by mohamedsabil83** [comment]
Good. I'll be waiting to hear from you.

**Comment by gwleuverink** [comment]
I've just tagged a minor release. @mohamedsabil83 If you experience anything out of the ordinary feel free to open a new issue

**Comment by mohamedsabil83** [comment]
Nice @gwleuverink, It's working as expected now :+1:
